# Hexo 配置文件
## 官方文档：https://hexo.io/docs/configuration.html
## 配置来源：https://github.com/hexojs/hexo/

# 网站信息
title: 细水长流 # 网站主标题
subtitle: '' # 网站副标题（显示在首页标题下方）
description: "一蓑烟雨任平生" # 网站描述（用于 SEO）
keywords: # 网站关键词（用于 SEO，可用英文逗号隔开）
author: Zhch's Blog # 作者名称
language: zh-CN # 网站语言（简体中文）
timezone: '' # 时区，留空表示使用系统默认时间

# 网址设置
## 设置你的网站主网址。如果是 GitHub Pages，设为 'https://用户名.github.io/仓库名'
url: https://zhchhe.github.io/BlogActions/
permalink: :year/:month/:day/:title/ # 文章永久链接格式
permalink_defaults: # 永久链接默认值
pretty_urls:
  trailing_index: true # 是否保留 index.html
  trailing_html: true # 是否保留 .html 后缀

# 目录设置
source_dir: source # 源文件目录
public_dir: public # 生成后静态文件目录
tag_dir: tags # 标签目录名
archive_dir: archives # 归档目录名
category_dir: categories # 分类目录名
code_dir: downloads/code # 代码文件保存目录（非默认使用）
i18n_dir: :lang # 多语言目录结构
skip_render: # 设置跳过渲染的文件或目录

# 写作配置
new_post_name: :title.md # 新建文章的文件命名方式
default_layout: post # 默认布局模板
titlecase: false # 是否将标题转换为标题格式（每个单词首字母大写）
external_link:
  enable: true # 是否自动在新标签页打开外部链接
  field: site # 设置作用范围（site 表示整站）
  exclude: '' # 不应用该规则的外部链接
filename_case: 0 # 文件名大小写：0-不变，1-全部小写，2-全部大写
render_drafts: false # 是否渲染草稿
post_asset_folder: false # 是否为每篇文章使用独立资源文件夹
relative_link: false # 是否启用相对链接
future: true # 是否显示未来日期的文章
syntax_highlighter: highlight.js # 语法高亮器（可选：highlight.js、prismjs 等）

# Highlight.js 配置
highlight:
  line_number: true # 显示行号
  auto_detect: false # 是否自动检测语言
  tab_replace: '' # 替换 tab 字符
  wrap: true # 是否自动换行
  hljs: false # 是否启用 highlight.js 样式类（若主题自带则设为 false）

# PrismJS 配置
prismjs:
  preprocess: true # 是否预处理 PrismJS 代码块
  line_number: true # 是否显示行号
  tab_replace: '' # 替换 tab 字符

# 首页设置
index_generator:
  path: '' # 首页路径（默认留空）
  per_page: 10 # 每页文章数量
  order_by: -date # 排序方式（按日期倒序）

# 分类与标签
default_category: uncategorized # 默认分类名
category_map: # 分类名称映射
tag_map: # 标签名称映射

# 元数据标签
meta_generator: true # 是否生成 <meta name="generator" content="Hexo"> 标签

# 日期与时间格式
date_format: YYYY-MM-DD # 日期显示格式
time_format: HH:mm:ss # 时间显示格式
updated_option: 'mtime' # 更新时间字段（mtime: 文件修改时间）

# 分页设置
per_page: 10 # 每页显示的文章数量
pagination_dir: page # 分页目录名称（用于分页 URL）

# 文件包含与排除（仅对 source/ 文件夹生效）
include: # 强制包含的文件
exclude: # 排除的文件
ignore:  # 忽略的文件或目录（通常用于版本控制）

# 扩展
## 插件安装地址：https://hexo.io/plugins/
## 主题安装地址：https://hexo.io/themes/
theme: next # 使用的主题（你安装的主题文件夹名称）

# 部署设置
## 官方文档：https://hexo.io/docs/one-command-deployment
deploy:
  type: '' # 部署方式，如 git、rsync、ftp 等（需对应插件支持）
